# Generated by Django 4.0 on 2022-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='only_matche',
            new_name='only_match',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=8, verbose_name='交友性别'),
        ),
    ]
